<br /><br />
<?php
	// echo $this->channel->title();
//        die(var_dump($this->baseUrl()));
	foreach ($this->channel as $channel) {
//   
            ?>
     <div class="post-preview">
                    <a href="#">
                        <h2 class="post-title">
                            <?php echo $channel['title'];  ?>
                        </h2>
                        <h3 class="post-subtitle">
                            <?php echo $channel['description'];  ?>
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#"><?php echo $channel['cat'];  ?></a><?php echo $channel['pubDate'];  ?></p>
                </div>
                <hr>
                <?php
}
?>	
<!--                
                -->